-- Deprecated migration script (status columns removed from base schema).
-- is_visible is now part of the initial table definitions in databaseweb.sql.
-- This file retained only for historical reference and should NOT be executed
-- on a fresh schema. If upgrading an old schema that still has status and
-- lacks is_visible, perform manual ALTERs:
--   ALTER TABLE pets ADD COLUMN is_visible TINYINT(1) NOT NULL DEFAULT 1 AFTER price, ADD INDEX idx_pets_visible (is_visible);
--   ALTER TABLE accessories ADD COLUMN is_visible TINYINT(1) NOT NULL DEFAULT 1 AFTER price, ADD INDEX idx_accessories_visible (is_visible);
-- Then optionally set all existing rows visible:
--   UPDATE pets SET is_visible = 1 WHERE is_visible IS NULL;
--   UPDATE accessories SET is_visible = 1 WHERE is_visible IS NULL;
-- Verification queries:
--   SELECT 'pets' AS tbl, COUNT(*) total, SUM(is_visible) visible, COUNT(*)-SUM(is_visible) hidden FROM pets;
--   SELECT 'accessories' AS tbl, COUNT(*) total, SUM(is_visible) visible, COUNT(*)-SUM(is_visible) hidden FROM accessories;
